version: '3.3'

services:
  mariadb:  
    container_name: ${DB_HOST}
    image: mariadb:latest
    restart: always
    ports: 
      - 3306:3306
    environment:
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASSWORD}
      MARIADB_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
    volumes:
      - ./dbdata:/var/lib/mysql

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: ${DB_HOST}
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: 100M
      PHP_MAX_INPUT_VARS: 10000
    ports:
      - 8080:80
    depends_on:
      - mariadb  

volumes:
  dbdata:
    driver: local